version: '3'
services:
  app:
    build: ./docker
    entrypoint: ./docker/entrypoint.sh
    container_name: nest_course_mongo
    environment: 
      - MONGODB_CONNSTRING=mongodb://zero:zero@mongodb
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
    depends_on:
      - mongo
    networks:
      - mongo

  mongo:
    image: mongo
    container_name: mongo_course
    ports:
      - '27017:27017'
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=zero
      - MONGO_INITDB_ROOT_PASSWORD=zero
    networks:
      - mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://zero:zero@mongo:27017/
    networks:
      - mongo


networks:
  mongo:
    driver: bridge
