version: '3'
services:
  app:
    build: ./docker
    entrypoint: ./docker/entrypoint.sh
    container_name: nest_course
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app 
    depends_on:
      - db
    networks:
      - postgres

  db:
    build: ./docker/postgres
    container_name: postgres_course
    restart: always
    tty: true
    ports:
      - '3001:5432'
    volumes:
      - ./docker/database/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_course
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '8000:80'
    depends_on:
      - db
    networks:
      - postgres
  
  dbtest:
    build: ./docker/postgres
    container_name: postgres_test_course
    restart: always
    tty: true
    ports:
      - '3002:5432'
    volumes:
      - ./docker/databasetest/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
